[package]
name = "chomp"
version = "0.1.0"
authors = ["Greg Brown <gmb60@cam.ac.uk>"]
edition = "2018"

[workspace]
members = ["autochomp", "chewed", "chomp-macro"]

[dependencies]
heck = "0.3.2"
proc-macro2 = "1.0.24"
quote = "1.0.8"
syn = "1.0.58"
