[package]
name = "autochomp"
version = "0.1.0"
authors = ["Greg Brown <gmb60@cam.ac.uk>"]
edition = "2018"

[build-dependencies]
chomp = {path = ".."}

[build-dependencies.syn]
version = "1"
features = ["extra-traits"]

[dependencies]
chewed = {path = "../chewed"}
