[package]
name = "chomp-macro"
version = "0.1.0"
authors = ["Greg Brown <gmb60@cam.ac.uk>"]
edition = "2018"

[dev-dependencies]
chewed = {path = "../chewed"}

[dependencies]
chomp = {path = ".."}

[dependencies.syn]
version = "1.0.58"
features = ["parsing", "proc-macro"]

[lib]
proc_macro = true
